import type { MarketProductGroup } from './types'

/** Orden de desempate cuando varios grupos coinciden con la misma puntuación. */
export const GROUP_CLASSIFY_PRIORITY: Exclude<MarketProductGroup, 'otros'>[] = [
  'carne',
  'lacteos',
  'frutas-verduras',
  'panaderia',
  'bebidas',
  'aseo',
]

export const MARKET_PRODUCT_KEYWORDS: Record<
  Exclude<MarketProductGroup, 'otros'>,
  string[]
> = {
  carne: [
    // Proteína — ES
    'carne molida',
    'carne de res',
    'carne de cerdo',
    'pechuga de pollo',
    'muslo de pollo',
    'hamburguesa',
    'salchicha',
    'chorizo',
    'morcilla',
    'jamón',
    'jamon',
    'mortadela',
    'salchichón',
    'salchichon',
    'tocino',
    'cordero',
    'cerdo',
    'pollo',
    'pescado',
    'salmón',
    'salmon',
    'atún',
    'atun',
    'trucha',
    'merluza',
    'camarón',
    'camaron',
    'langostino',
    'huevo',
    'huevos',
    'carne',
    'res',
    'filete',
    'muslo',
    'pechuga',
    // Proteína — EN
    'chicken breast',
    'chicken thigh',
    'chicken drumstick',
    'chicken wing',
    'chicken tender',
    'chicken mince',
    'beef mince',
    'pork mince',
    'lamb chop',
    'lamb leg',
    'pork chop',
    'pork belly',
    'bacon rashers',
    'smoked salmon',
    'tuna steak',
    'prawn cutlet',
    'seafood mix',
    'deli ham',
    'leg ham',
    'shaved ham',
    'salami',
    'prosciutto',
    'chorizo',
    'meat pie',
    'chicken',
    'beef',
    'pork',
    'lamb',
    'steak',
    'mince',
    'sausage',
    'bacon',
    'turkey',
    'duck',
    'venison',
    'kangaroo',
    'fish',
    'salmon',
    'tuna',
    'prawn',
    'prawns',
    'shrimp',
    'seafood',
    'fillet',
    'thigh',
    'breast',
    'drumstick',
    'meat',
    'protein',
    'egg',
    'eggs',
    'ham',
    'barramundi',
    'snapper',
    'cod',
    'sardine',
    'anchovy',
    'calamari',
    'squid',
    'octopus',
    'crab',
    'lobster',
    'tofu',
    'tempeh',
  ],
  aseo: [
    // Aseo — ES
    'papel higiénico',
    'papel higienico',
    'papel toalla',
    'jabón de baño',
    'jabon de bano',
    'jabón líquido',
    'jabon liquido',
    'lavaplatos',
    'suavizante',
    'desinfectante',
    'limpiador',
    'detergente',
    'quitamanchas',
    'blanqueador',
    'cloro',
    'bolsa de basura',
    'bolsa reutilizable',
    'pañal',
    'panal',
    'toallitas',
    'champú',
    'champu',
    'acondicionador',
    'cepillo de dientes',
    'pasta dental',
    'desodorante',
    'jabón',
    'jabon',
    'esponja',
    'servilleta',
    'bolsa',
    'aseo',
    'ariel',
    'fabuloso',
    'lyso',
    'vanish',
    'raid',
    // Aseo — EN
    'toilet paper',
    'paper towel',
    'facial tissue',
    'dishwashing liquid',
    'dish washing',
    'dish soap',
    'dishwash',
    'fabric softener',
    'laundry liquid',
    'laundry powder',
    'stain remover',
    'toilet cleaner',
    'bathroom cleaner',
    'glass cleaner',
    'multi purpose cleaner',
    'disinfectant',
    'antibacterial',
    'hand sanitiser',
    'hand sanitizer',
    'body wash',
    'shower gel',
    'hand wash',
    'tooth paste',
    'toothpaste',
    'mouth wash',
    'mouthwash',
    'deodorant',
    'antiperspirant',
    'feminine hygiene',
    'incontinence',
    'garbage bag',
    'rubbish bag',
    'plastic wrap',
    'aluminium foil',
    'baking paper',
    'glad wrap',
    'baby wipes',
    'wet wipes',
    'detergent',
    'bleach',
    'cleaner',
    'cleaning',
    'conditioner',
    'shampoo',
    'soap',
    'sanitiser',
    'sanitizer',
    'wipes',
    'laundry',
    'sponge',
    'napkin',
    'nappy',
    'diaper',
    'tissue',
    'hygiene',
    'tide',
    'palmolive',
    'dettol',
    'finish',
    'harpic',
    'pine o cleen',
    'sorbent',
    'kleenex',
    'quilton',
  ],
  'frutas-verduras': [
    // Frescos — ES
    'frutas y verduras',
    'fruta fresca',
    'verdura fresca',
    'papa criolla',
    'papa pastusa',
    'yuca',
    'ñame',
    'name',
    'tomate cherry',
    'tomate chonto',
    'plátano',
    'platano',
    'banano',
    'aguacate',
    'zanahoria',
    'lechuga',
    'espinaca',
    'brócoli',
    'brocoli',
    'coliflor',
    'pepino',
    'apio',
    'remolacha',
    'habichuela',
    'frijol',
    'lenteja',
    'arveja',
    'guisante',
    'champiñón',
    'champinon',
    'hongo',
    'manzana',
    'pera',
    'naranja',
    'mandarina',
    'limón',
    'limon',
    'fresa',
    'frutilla',
    'mora',
    'uva',
    'mango',
    'piña',
    'pina',
    'papaya',
    'maracuyá',
    'maracuya',
    'granadilla',
    'lulo',
    'tomate',
    'cebolla',
    'ajo',
    'papa',
    'fruta',
    'verdura',
    // Frescos — EN
    'fresh produce',
    'salad mix',
    'mixed salad',
    'baby spinach',
    'sweet potato',
    'red onion',
    'brown onion',
    'spring onion',
    'green onion',
    'bok choy',
    'pak choy',
    'snow peas',
    'sugar snap',
    'green beans',
    'brussels sprout',
    'rockmelon',
    'honeydew',
    'cantaloupe',
    'watermelon',
    'passionfruit',
    'dragon fruit',
    'kiwi fruit',
    'blueberry',
    'raspberry',
    'strawberry',
    'blackberry',
    'cherry tomato',
    'cos lettuce',
    'iceberg lettuce',
    'rocket lettuce',
    'herb pot',
    'fresh herb',
    'vegetable',
    'capsicum',
    'bell pepper',
    'zucchini',
    'cucumber',
    'broccoli',
    'cauliflower',
    'asparagus',
    'mushroom',
    'avocado',
    'pineapple',
    'banana',
    'tomato',
    'onion',
    'potato',
    'carrot',
    'lettuce',
    'spinach',
    'cabbage',
    'celery',
    'pumpkin',
    'corn cob',
    'sweet corn',
    'apple',
    'pear',
    'orange',
    'lemon',
    'lime',
    'grape',
    'mango',
    'fruit',
    'berries',
    'salad',
    'herb',
    'garlic',
    'ginger',
    'beetroot',
    'parsnip',
    'turnip',
    'radish',
    'leek',
    'shallot',
    'eggplant',
    'aubergine',
    'cabbage',
    'kale',
    'silverbeet',
    'chard',
    'beans',
    'peas',
  ],
  lacteos: [
    // Lácteos — ES
    'leche entera',
    'leche deslactosada',
    'leche descremada',
    'leche de almendra',
    'leche de soya',
    'queso campesino',
    'queso costeño',
    'queso mozzarella',
    'queso parmesano',
    'queso crema',
    'mantequilla',
    'margarina',
    'yogurt griego',
    'yogur griego',
    'natilla',
    'arequipe',
    'kumis',
    'crema de leche',
    'leche condensada',
    'leche evaporada',
    'leche',
    'queso',
    'yogurt',
    'yogur',
    'crema',
    // Lácteos — EN
    'full cream milk',
    'lite milk',
    'light milk',
    'skim milk',
    'lactose free milk',
    'almond milk',
    'soy milk',
    'oat milk',
    'coconut milk drink',
    'cream cheese',
    'sour cream',
    'whipping cream',
    'thickened cream',
    'pure cream',
    'greek yoghurt',
    'greek yogurt',
    'natural yoghurt',
    'cheddar cheese',
    'tasty cheese',
    'mozzarella cheese',
    'parmesan cheese',
    'feta cheese',
    'brie cheese',
    'camembert',
    'ricotta cheese',
    'cottage cheese',
    'butter',
    'margarine',
    'custard',
    'milk',
    'cheese',
    'yoghurt',
    'yogurt',
    'dairy',
    'cheddar',
    'mozzarella',
    'parmesan',
    'feta',
    'ricotta',
    'brie',
    'haloumi',
    'halloumi',
    'provolone',
    'colby',
  ],
  panaderia: [
    // Panadería y despensa — ES
    'pan integral',
    'pan blanco',
    'pan tajado',
    'pan de molde',
    'arepa',
    'tortilla de maíz',
    'tortilla de maiz',
    'galleta',
    'galletas',
    'pastel',
    'torta',
    'brownie',
    'muffin',
    'croissant',
    'bagel',
    'empanada',
    'buñuelo',
    'bunuelo',
    'achiras',
    'avena',
    'harina',
    'arroz',
    'pasta',
    'fideo',
    'fideos',
    'spaghetti',
    'macarrones',
    'cereal',
    'granola',
    'muesli',
    'chocolate',
    'dulce',
    'snack',
    'papas fritas',
    'maní',
    'mani',
    'nuez',
    'almendra',
    'aceite',
    'azúcar',
    'azucar',
    'pan',
    'tortilla',
    'bollo',
    // Panadería — EN
    'sliced bread',
    'wholemeal bread',
    'white bread',
    'sourdough bread',
    'garlic bread',
    'bread roll',
    'dinner roll',
    'hot cross bun',
    'english muffin',
    'pita bread',
    'flat bread',
    'wrap bread',
    'rice cakes',
    'corn chips',
    'potato chips',
    'tortilla chips',
    'snack pack',
    'muesli bar',
    'protein bar',
    'chocolate bar',
    'tim tam',
    'shapes biscuit',
    'weet bix',
    'corn flakes',
    'nutri grain',
    'pasta sauce',
    'tomato sauce',
    'pasta',
    'spaghetti',
    'penne',
    'macaroni',
    'noodles',
    'instant noodles',
    'rice',
    'jasmine rice',
    'basmati rice',
    'brown rice',
    'flour',
    'self raising flour',
    'plain flour',
    'cereal',
    'oats',
    'granola',
    'muesli',
    'biscuit',
    'cookie',
    'cracker',
    'chips',
    'crisps',
    'popcorn',
    'peanut butter',
    'jam',
    'vegemite',
    'nutella',
    'honey',
    'sugar',
    'brown sugar',
    'olive oil',
    'vegetable oil',
    'canola oil',
    'coconut oil',
    'cooking oil',
    'vinegar',
    'bread',
    'bun',
    'roll',
    'loaf',
    'cake',
    'muffin',
    'pastry',
    'wrap',
    'pita',
    'flatbread',
    'crumpet',
    'scone',
    'donut',
    'doughnut',
    'pie',
    'bakery',
    'snack',
    'chocolate',
    'nuts',
    'almond',
    'walnut',
    'cashew',
  ],
  bebidas: [
    // Bebidas — ES
    'agua mineral',
    'agua con gas',
    'agua sin gas',
    'jugo natural',
    'jugo de naranja',
    'jugo de mango',
    'bebida gaseosa',
    'gaseosa',
    'refresco',
    'cerveza',
    'vino tinto',
    'vino blanco',
    'whisky',
    'ron',
    'aguardiente',
    'café',
    'cafe',
    'té',
    'te',
    'infusión',
    'infusion',
    'agua',
    'jugo',
    'cerveza',
    'vino',
    'bebida',
    'cola',
    'sprite',
    'soda',
    // Bebidas — EN
    'sparkling water',
    'mineral water',
    'still water',
    'coconut water',
    'orange juice',
    'apple juice',
    'fruit juice',
    'cold pressed juice',
    'soft drink',
    'energy drink',
    'sports drink',
    'iced coffee',
    'iced tea',
    'long life milk drink',
    'flavoured milk',
    'chocolate milk',
    'ginger beer',
    'tonic water',
    'soda water',
    'red wine',
    'white wine',
    'sparkling wine',
    'prosecco',
    'champagne',
    'bourbon',
    'scotch whisky',
    'premix can',
    'rtd can',
    'water',
    'juice',
    'beer',
    'wine',
    'spirit',
    'vodka',
    'whisky',
    'whiskey',
    'gin',
    'rum',
    'coke',
    'pepsi',
    'fanta',
    'sprite',
    'cordial',
    'coffee',
    'tea',
    'drink',
    'beverage',
    'lemonade',
    'kombucha',
    'red bull',
    'v energy',
    'powerade',
    'gatorade',
    'sparkling',
    'cola',
  ],
}

export function normalizeProductName(name: string): string {
  return name
    .toLowerCase()
    .normalize('NFD')
    .replace(/\p{M}/gu, '')
    .replace(/[^a-z0-9\s]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

export function keywordMatchesProduct(normalized: string, keyword: string): boolean {
  const nkw = keyword
    .toLowerCase()
    .normalize('NFD')
    .replace(/\p{M}/gu, '')
    .trim()

  if (!nkw) return false

  if (nkw.includes(' ')) {
    return normalized.includes(nkw)
  }

  const re = new RegExp(`(?:^|\\s)${escapeRegExp(nkw)}(?:\\s|$)`)
  return re.test(` ${normalized} `)
}

export function classifyProductName(name: string): MarketProductGroup {
  const normalized = normalizeProductName(name)
  if (!normalized) return 'otros'

  let bestGroup: MarketProductGroup = 'otros'
  let bestScore = 0

  for (const group of GROUP_CLASSIFY_PRIORITY) {
    const keywords = MARKET_PRODUCT_KEYWORDS[group]
    let groupScore = 0

    for (const kw of keywords) {
      if (keywordMatchesProduct(normalized, kw)) {
        groupScore = Math.max(groupScore, kw.length)
      }
    }

    if (groupScore > bestScore) {
      bestScore = groupScore
      bestGroup = group
    }
  }

  return bestGroup
}
